version: "3.9"
services:
  backend:
    build: { context: ./backend }
    environment:
      APP_PORT: 8080
      DB_URL: ${DB_URL}
      CORS_ORIGINS: ${CORS_ORIGINS:-*}
    ports: ["8080:8080"]
    restart: unless-stopped

  frontend:
    build: { context: ./frontend }
    ports: ["80:80"]
    restart: unless-stopped
