version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bdu_inventory
    ports: ["3306:3306"]
    volumes: [ "dbdata:/var/lib/mysql" ]

  backend:
    build: { context: ./backend }
    environment:
      APP_PORT: 8080
      DB_URL: mysql+aiomysql://root:secret@db:3306/bdu_inventory
      CORS_ORIGINS: http://localhost:5173,http://127.0.0.1:5173
    volumes: [ "./backend:/app" ]
    command: ["uvicorn","app.main:app","--host","0.0.0.0","--port","8080","--reload"]
    ports: ["8080:8080"]
    depends_on: [ db ]

  frontend:
    build:
      context: ./frontend
      target: build
    working_dir: /app
    environment:
      VITE_API_BASE_URL: http://localhost:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm","run","dev","--","--host","0.0.0.0"]
    ports: ["5173:5173"]
    depends_on: [ backend ]

volumes: { dbdata: {} }
